name: take_me_user
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^1.0.3
  url_launcher:
  shared_preferences:
  google_maps_flutter:
  geolocator:
  flutter_google_places:
  awesome_dialog:
  location:
  geocoding: ^2.0.4
  firebase_analytics: ^9.1.9
  firebase_crashlytics: ^2.8.1
  firebase_installations: ^16.3.6
  firebase_core_dart: ^1.0.0
  http: ^0.13.4
  smart_alert_dialog: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true




